- name: install mariadb server
  package:
    name: mariadb-server
    state: present

- name: start mariadb
  systemd:
    name: mariadb
    enabled: yes
    state: started

- name: download the sql file (database schema)
  get_url:
    url: "{{DBURL}}"
    dest: "/tmp/studentapp.sql"

#- name: Restore database
#  mysql_db:
#    name: studentapp
#    state: import
#    target: /tmp/studentapp.sql

#- name: Load Schema
# shell: mysql </tmp/studentapp.sql
