- name: files
  file:
    dest: "/home/centos/tomcat/tomcat-{{ item1 }}"
    state: directory

- name: download tomcat in tomcat-{{item1}}
  unarchive:
    dest: "/home/{{APPUSER}}/tomcat/tomcat-{{item1}}"
    src: "{{TOMCAT_URL}}"
    remote_src: yes
  become_user: "{{APPUSER}}"