- name: create tomcat-{{ item }}
  file:
    dest: "/home/centos/tomcat/tomcat-{{ item }}"
    state: directory

- name: download tomcat in tomcat-{{item}}
  unarchive:
    dest: "/home/{{APPUSER}}/tomcat/tomcat-{{item}}"
    src: "{{TOMCAT_URL}}"
    remote_src: yes
  become_user: "{{APPUSER}}"

- name: edit the context.xml file to specify the DataBase details using template
  template:
    src: server.xml.j2
    dest: "/home/{{APPUSER}}/tomcat/tomcat-{{item}}/apache-tomcat-{{TOMCAT_VERSION}}/conf/server.xml"
  become_user: "{{APPUSER}}"