- name: create tomcat-{{ item }} directory
  file:
    dest: "/home/centos/tomcat/tomcat-{{ item }}"
    state: directory

- name: download tomcat in tomcat-{{item}} directory
  unarchive:
    dest: "/home/{{APPUSER}}/tomcat/tomcat-{{item}}"
    src: "{{TOMCAT_URL}}"
    remote_src: yes
  become_user: "{{APPUSER}}"

- name: edit the context.xml file to specify the DataBase details using template
  template:
    src: server.xml.j2
    dest: "/home/{{APPUSER}}/tomcat/tomcat-{{item}}/apache-tomcat-{{TOMCAT_VERSION}}/conf/server.xml"
  become_user: "{{APPUSER}}"

#- name: download tomcat init script to configure systemctl
#  template:
#    src: tomcat-init.j2
#    dest: "/etc/init.d/tomcat"
#    mode: u=rwx,g=rx,o=rx
#
#
#- name: Reload systemctl services
#  systemd:
#    daemon_reload: yes
#
#- name: start tomcat
#  systemd:
#    name: tomcat
#    state: started

- name: start tomcat{{item}}
  shell:
    cmd: sh /home/{{APPUSER}}/tomcat/tomcat-{{item}}/apache-tomcat-{{TOMCAT_VERSION}}/bin/startup.sh
