- name: Print a variable from play
  hosts: all
  vars:
    URL: play.google.com
  tasks:
    - name: print a variable
      debug:
        msg: "URL= {{URL}}"

- name: Print a variable from task
  hosts: all
  tasks:
    - name: print a variable
      vars:
        URL: task.google.com
      debug:
        msg: "URL= {{URL}}"

- name: print a variable from a file
  hosts: all
  vars_files:
    - varfile.yml
  tasks:
    - name: Print a value from vars file
      debug:
        msg: URL = {{URL}}

- name: take input from the user prompt and display
  hosts: all
  vars_prompt:
    - name: URL
      prompt: Enter the value
  tasks:
    - name: Print a value from vars file
      debug:
        msg: URL = {{URL}}