- name: Install & Configure web server
  hosts: all
  vars_prompt:
    - name: number
      prompt: Enter the number of times to iterate the loop
      private: no
  tasks:
    - name: find all the nginx files
      find:
        paths: /home/centos/
        file_type: any
      register: OUT

    - name: delete the files in html directory
      file:
        path: "{{item.path}}"
        state: absent
      loop: "{{OUT.files}}"

    - name: roles
      include_role:
        name: download_tomcat
      vars:
        item1: "{{item}}"
      with_sequence: end={{number}} start=1
