- name: Install & Configure web server
  hosts: all
  vars_prompt:
    - name: number
      prompt: Enter the number of times to iterate the loop
      private: no
  tasks:
    - name: roles
      include_role:
        name: download_tomcat
      vars:
        item1: "{{item}}"
      with_sequence: end={{number}} start=1
    - name: files
      file:
        dest: "/home/centos/tomcat/tomcat-{{ item }}"
        state: directory