- name: Install & Configure web server
  hosts: all
  vars_prompt:
    - name: number
      prompt: Enter the number of times to iterate the loop
      private: no
  - name: roles
    include_role:
      name: download_tomcat
    vars:
      item: "{{item}}"
    with_sequence: end={{number}} start=1