- name: Install & Configure {{number}} tomcat servers
  hosts: all
  vars_prompt:
    - name: number
      prompt: Enter the number of tomcat-servers
      private: no
  tasks:
    - name: install java
      package:
        name: java
        state: latest
      become: yes
    - name: find all the tomcat directories
      find:
        paths: /home/centos/
        file_type: any
      register: OUT

    - name: delete all tomcat directories
      file:
        path: "{{item.path}}"
        state: absent
      loop: "{{OUT.files}}"
      become: yes

    - name: download tomcat role
      include_role:
        name: download_tomcat
      vars:
        item1: "{{item}}"
      with_sequence: end={{number}} start=1

    - name: download tomcat init script to configure systemctl
      get_url:
        url: "https://s3-us-west-2.amazonaws.com/studentapi-cit/tomcat-init"
        dest: "/etc/init.d/tomcat"
        mode: u=rwx,g=rx,o=rx

    - name: Reload systemctl services
      systemd:
        daemon_reload: yes

    - name: start tomcat
      systemd:
        name: tomcat
        state: started
