- name: Install & Configure web server
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx Web Server
      package:
        name: nginx
        state: present

    - name: find all the nginx files
      find:
        paths: /usr/share/nginx/html/
        file_type: any
      register: OUT

    - name: delete the files in html directory
      file:
        path: "{{item.path}}"
        state: absent
      loop: "{{OUT.files}}"

    - name: download the file and copy into html directory
      unarchive:
        src: https://studentapi-cit.s3-us-west-2.amazonaws.com/studentapp-frontend.tar.gz
        dest: /usr/share/nginx/html
        remote_src: yes
    - name: Starting nginx service
      service:
        name: nginx
        state: restarted
        enabled: yes